package mapper;

import entity.t_role;
import entity.t_roleExample;
import java.util.List;

public interface t_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Wed Jun 09 13:14:28 CST 2021
     */
    int countByExample(t_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Wed Jun 09 13:14:28 CST 2021
     */
    List<t_role> selectByExample(t_roleExample example);
}